### ISSUE TITLE
Unicode chacter problem

### ISSUE THREAD

**Issue by gokhanm** [kvesteri/validators#14] opened 2016-01-02 10:41 UTC
I have a encode domain like "xn----gtbspbbmkef.xn--p1ai"
it is valid domain but validators raise ValidationFailure

>>> a = idna.decode('xn----gtbspbbmkef.xn--p1ai')
>>> validators.domain(a)
ValidationFailure(func=domain, args={'value': 'доктор-ост.рф'})

Another problem, underline subnet domains
>>> validators.domain('victor_caffarena.tripod.com')
ValidationFailure(func=domain, args={'value': 'victor_caffarena.tripod.com'})

**Comment by kvesteri** [comment] 2016-01-08 18:52
Thanks for reporting this. The problem is with the regex I've used. I tried googling for alternatives but none of the ones I found could validate the following test cases:

VALID domains:

example.com
xn----gtbspbbmkef.xn--p1ai
underscore_subdomain.example.com
something.versicherung

INVALID domains:

example.com/
example.com:4444
example.-com
example.
example

**Comment by kvesteri** [comment] 2016-01-09 09:06
Found a good regex. Now fixed (as of version 0.10).

**Closed by kvesteri** 2016-01-09 09:06 UTC
